github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    branches: true

image:
  file: .gitpod/gitpod.Dockerfile

tasks:
  - command: |
      # Install commitlint
      npm i -g @commitlint/{config-conventional,cli}

      # Install husky
      npm i -g husky

      # Activate hooks
      husky install

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - HashiCorp.terraform
