github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    branches: true

image:
  file: .gitpod/gitpod.Dockerfile

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - HashiCorp.terraform
