---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gitpod-issuer
spec:
  acme:
    email: $LETSENCRYPT_EMAIL
    privateKeySecretRef:
      name: issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            region: us-west-1
            accessKeyID: ${ROUTE53_ACCESS_KEY}
            secretAccessKeySecretRef:
              name: route53-api-secret
              key: secret-access-key
